# -*- coding: utf-8 -*-
"""LSTM_TS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130UqXM1MHFMP_vyYdDvN_UD2Py_X-uum
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM



df = df.rename(columns={'Monthly milk production (pounds per cow)': 'production'})

df.head()

df.tail()

df.plot(figsize=(12, 6))

